### ISSUE TITLE
Example using logging

### ISSUE THREAD

**Issue by bfleming-ciena** [dzanotelli/drypy#15]
Close this out if it's unreasonable.  I need to learn the logging module, but my initial attempts aren't working. I know I'll get it soon, but it would be great if you could add a few lines in the doc to show a minimal log setup needed so I can at least see some output when trying your examples.

tnx

**Comment by dzanotelli** [comment]
Ok reasonable, i'll add an example, thanks for your suggestion. 
Just a fast tip: remember that python logging facility filters both with the logger level and the handler level. Thus to see INFO level messages (the drypy level) you must set at least to INFO both the logger and the handler. 
eg:
```
import logging
from drypy import dryrun
from drypy.patterns import sham

logger = logging.getLogger('drypy')
logger.setLevel(logging.INFO)
h = logging.StreamHandler()  # print to console
h.setLevel(logging.INFO)
logger.addHandler(h)

@sham
def do_something():
     print('hello')

do_something()
# now activate dryrun
dryrun(True)
do_something()
```
and you should see at console:
```
hello
[DRYRUN] call to 'do_something()'
```
hope this help, 
best D.

**Comment by bfleming-ciena** [comment]
Got it, thanks a lot, really. I was pretty close, I must have left one part out of that.  Thanks again.
